### ISSUE TITLE
auto build package

### ISSUE THREAD

**Issue by soleil0-0** [soleil0-0/GazelleSync#17]
## Details
- use CI to build package

### Travis CI
<details><summary>.travis.yml</summary>

```yaml
language: python
jobs:
  include:
    # - name: "Python 3.7.4 on Xenial Linux"
    #   python: 3.7.4
    #   before_install:
    #     - sudo apt-get -y install libgtk-3-dev libglu1-mesa-dev
    #     - pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04 wxPython
    #   env:
    #     - DEPLOY_FILE=dist/gs_linux_amd64.zip
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2            # Python 3.7.4 running on macOS 10.14.4
      language: shell                 # 'language: python' is an error on Travis CI macOS
      env:
        - DEPLOY_FILE=dist/gs_darwin_amd64.zip
    - name: "Python 3.7.4 on Windows"
      os: windows                     # Windows 10.0.17134 N/A Build 17134
      language: shell                 # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.4
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - DEPLOY_FILE=dist/gs_windows_amd64.zip
install:
  - python -m pip install -U pip
  - pip install -U pipenv
  - pipenv install --three --dev --skip-lock
  - pipenv graph
script:
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      pipenv run build_osx
    elif [ "$TRAVIS_OS_NAME" = "linux" ]; then
      #pipenv run build_linux
      echo TODO
    elif [ "$TRAVIS_OS_NAME" = "windows" ]; then
      pipenv run build_win
    fi
deploy:
  provider: releases
  api_key:
    secure: "$GITHUB_TOKEN_SECURE"
  file: "$DEPLOY_FILE"
  skip_cleanup: true
  draft: true
  on:
   tags: true

```

</details>

<details><summary>status badge</summary>

[![Build Status](https://travis-ci.org/soleil0-0/GazelleSync.svg?branch=master)](https://travis-ci.org/soleil0-0/GazelleSync)
```
[![Build Status](https://travis-ci.org/soleil0-0/GazelleSync.svg?branch=master)](https://travis-ci.org/soleil0-0/GazelleSync)
```

</details>

### Github Actions

<details><summary>.github/workflows/main.yml</summary>

```yaml
name: Upload Release Asset

on:
  push:
    tags:
      - "*"
  pull_request
  issues:
    types: [opened]

jobs:
  build_ubuntu:
    name: Build Release Asset - Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7.8"
      - name: Install packages
        run: sudo apt-get -y install libgtk-3-dev libglu1-mesa-dev
      - name: Install dependencies
        run: |
          pip install -U pipenv
          pipenv install --three --dev --skip-lock
      - name: Build project
        run: |
          echo TODO
      - uses: actions/upload-artifact@v2
        with:
          name: gs_linux_amd64.zip
          path: dist/gs_linux_amd64.zip

  build_macos:
    name: Build Release Asset - MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7.8"
      - name: Install dependencies
        run: |
          pip install -U pipenv
          pipenv install --three --dev --skip-lock
      - name: Build project
        run: pipenv run build_osx
      - uses: actions/upload-artifact@v2
        with:
          name: gs_darwin_amd64.zip
          path: dist/gs_darwin_amd64.zip

  build_windows:
    name: Build Release Asset - Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7.8"
      - name: Install dependencies
        run: |
          pip install -U pipenv
          pipenv install --three --dev --skip-lock
      - name: Build project
        run: |
          pipenv run build_win
      - uses: actions/upload-artifact@v2
        with:
          name: gs_windows_amd64.zip
          path: dist/gs_windows_amd64.zip

```

</details>

## Reference
- [Travis CI: Running Python tests on multiple Operating Systems](https://docs.travis-ci.com/user/languages/python/#running-python-tests-on-multiple-operating-systems)
  - [install wxPython](https://stackoverflow.com/questions/14007557/installing-wxpython-on-ubuntu-12-04#answer-49379934)
- [Github Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on)
  - [cross platform](https://www.edwardthomson.com/blog/github_actions_3_crossplatform_builds.html)
  - [new tag event](https://github.community/t/how-to-run-github-actions-workflow-only-for-new-tags/16075/22)
  - [act: GitHub Actions locally](https://github.com/nektos/act)
  - [GitHub Actions Manual Trigger](https://github.community/t/github-actions-manual-trigger-approvals/16233/42)
  - Upload multi assets from different os to a release
    - [github actions - support community](https://github.community/t/upload-multi-assets-from-different-os-to-a-release/17031)
    - [actions/upload-release-asset: Support matrix build](https://github.com/actions/upload-release-asset/issues/16)
      - [release.yml](https://github.com/studiorack/studiorack-plugin/blob/master/.github/workflows/release.yml)
  - [own runner](https://docs.github.com/en/actions/hosting-your-own-runners)
- [install python3-wxgtk on ubuntu](https://askubuntu.com/questions/1073145/how-to-install-wxpython-4-ubuntu-18-04/1073183#answer-1073183)
